run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - gofmt
    - goimports

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  errcheck:
    check-type-assertions: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
