package main

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	generatedAgentMarker    = "Generated by dotagents"
	readmeSkillsBeginMarker = "<!-- BEGIN GENERATED SKILLS -->"
	readmeSkillsEndMarker   = "<!-- END GENERATED SKILLS -->"
)

// agentRoleMarkdownExt is the editable starter role source format under
// agents/<name>.md. The YAML frontmatter holds metadata; the Markdown body is
// the role prompt.
const agentRoleMarkdownExt = ".md"

type agentRole struct {
	Name         string              `yaml:"name"`
	Description  string              `yaml:"description"`
	Model        string              `yaml:"model"`
	Effort       string              `yaml:"effort"`
	Tools        []string            `yaml:"tools"`
	Color        string              `yaml:"color"`
	Instructions string              `yaml:"-"`
	Source       string              `yaml:"-"`
	Codex        codexRoleOptions    `yaml:"codex"`
	Droid        droidRoleOptions    `yaml:"droid"`
	Opencode     opencodeRoleOptions `yaml:"opencode"`
}

func (role *agentRole) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("agent role must be a mapping")
	}
	for i := 0; i+1 < len(value.Content); i += 2 {
		key := value.Content[i].Value
		node := value.Content[i+1]
		switch key {
		case "name":
			if err := node.Decode(&role.Name); err != nil {
				return err
			}
		case "description":
			if err := node.Decode(&role.Description); err != nil {
				return err
			}
		case "model":
			if err := node.Decode(&role.Model); err != nil {
				return err
			}
		case "effort":
			if err := node.Decode(&role.Effort); err != nil {
				return err
			}
		case "color":
			if err := node.Decode(&role.Color); err != nil {
				return err
			}
		case "codex":
			if err := node.Decode(&role.Codex); err != nil {
				return err
			}
		case "droid":
			if err := node.Decode(&role.Droid); err != nil {
				return err
			}
		case "opencode":
			if err := node.Decode(&role.Opencode); err != nil {
				return err
			}
		case "tools":
			tools, err := decodeRoleTools(node)
			if err != nil {
				return err
			}
			role.Tools = tools
		}
	}
	return nil
}

func decodeRoleTools(node *yaml.Node) ([]string, error) {
	switch node.Kind {
	case yaml.SequenceNode:
		var tools []string
		if err := node.Decode(&tools); err != nil {
			return nil, err
		}
		return tools, nil
	case yaml.ScalarNode:
		var tools []string
		for _, part := range strings.Split(node.Value, ",") {
			if tool := strings.TrimSpace(part); tool != "" {
				tools = append(tools, tool)
			}
		}
		return tools, nil
	default:
		return nil, fmt.Errorf("tools must be a YAML sequence or comma-separated string")
	}
}

type codexRoleOptions struct {
	Model                string `yaml:"model"`
	ModelReasoningEffort string `yaml:"model_reasoning_effort"`
}

type droidRoleOptions struct {
	Model           string   `yaml:"model"`
	ReasoningEffort string   `yaml:"reasoning_effort"`
	Tools           []string `yaml:"tools"`
}

type opencodeRoleOptions struct {
	Model       string `yaml:"model"`
	Temperature string `yaml:"temperature"`
	Mode        string `yaml:"mode"`
}

var droidToolMapping = map[string][]string{
	"bash":      {"Execute"},
	"edit":      {"Edit"},
	"glob":      {"Glob"},
	"grep":      {"Grep"},
	"read":      {"Read"},
	"webfetch":  {"FetchUrl"},
	"websearch": {"WebSearch"},
	"write":     {"Create", "Edit"},
}

var droidFallbackTools = []string{"Read", "LS", "Grep", "Glob"}

type renderedAgentRole struct {
	Name    string
	Source  string
	Target  string
	Content string
}

func expectedAgentRoles(repoRoot string, agent agentConfig) (map[string]renderedAgentRole, error) {
	if agent.AgentRoot == "" {
		return map[string]renderedAgentRole{}, nil
	}

	roles, err := loadAgentRoles(repoRoot)
	if err != nil {
		return nil, err
	}

	rendered := make(map[string]renderedAgentRole)
	for _, role := range roles {
		target, content, ok := renderAgentRole(role, agent)
		if !ok {
			continue
		}
		rendered[role.Name] = renderedAgentRole{
			Name:    role.Name,
			Source:  role.Source,
			Target:  target,
			Content: content,
		}
	}
	return rendered, nil
}

func loadAgentRoles(repoRoot string) ([]agentRole, error) {
	agentsDir := filepath.Join(repoRoot, "agents")
	entries, err := os.ReadDir(agentsDir)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", agentsDir, err)
	}

	var paths []string
	for _, entry := range entries {
		if entry.IsDir() || strings.HasPrefix(entry.Name(), ".") || filepath.Ext(entry.Name()) != agentRoleMarkdownExt {
			continue
		}
		paths = append(paths, filepath.Join(agentsDir, entry.Name()))
	}
	sort.Strings(paths)
	return loadMarkdownAgentRoles(paths)
}

func loadMarkdownAgentRoles(paths []string) ([]agentRole, error) {
	roles := make([]agentRole, 0, len(paths))
	seen := make(map[string]struct{}, len(paths))
	for _, path := range paths {
		role, err := loadMarkdownAgentRole(path)
		if err != nil {
			return nil, err
		}
		if _, ok := seen[role.Name]; ok {
			return nil, fmt.Errorf("agent role %s is duplicated", role.Name)
		}
		seen[role.Name] = struct{}{}
		roles = append(roles, role)
	}
	sort.Slice(roles, func(i, j int) bool {
		return roles[i].Name < roles[j].Name
	})
	return roles, nil
}

func loadMarkdownAgentRole(path string) (agentRole, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return agentRole{}, fmt.Errorf("read %s: %w", path, err)
	}
	role, err := parseAgentRoleMarkdown(path, data)
	if err != nil {
		return agentRole{}, err
	}
	if err := finalizeAgentRole(&role, path); err != nil {
		return agentRole{}, err
	}
	return role, nil
}

func parseAgentRoleMarkdown(path string, data []byte) (agentRole, error) {
	if !bytes.HasPrefix(data, []byte("---\n")) {
		return agentRole{}, fmt.Errorf("%s: missing YAML frontmatter", path)
	}
	rest := data[len("---\n"):]
	end := bytes.Index(rest, []byte("\n---"))
	if end < 0 {
		return agentRole{}, fmt.Errorf("%s: unterminated YAML frontmatter", path)
	}
	frontmatter := rest[:end]
	body := rest[end+len("\n---"):]
	if len(body) > 0 && body[0] == '\r' {
		body = body[1:]
	}
	if len(body) > 0 && body[0] == '\n' {
		body = body[1:]
	}
	var role agentRole
	if err := yaml.Unmarshal(frontmatter, &role); err != nil {
		return agentRole{}, fmt.Errorf("parse %s frontmatter: %w", path, err)
	}
	role.Instructions = strings.TrimSpace(string(body))
	role.Source = path
	return role, nil
}

func finalizeAgentRole(role *agentRole, source string) error {
	role.Name = normalizeAgentName(role.Name)
	role.Model = strings.TrimSpace(role.Model)
	role.Effort = strings.TrimSpace(role.Effort)
	role.Description = strings.TrimSpace(role.Description)
	role.Instructions = strings.TrimSpace(role.Instructions)
	if role.Name == "" {
		return fmt.Errorf("%s is missing name", source)
	}
	if role.Description == "" {
		return fmt.Errorf("%s: role %s is missing description", source, role.Name)
	}
	if role.Instructions == "" {
		return fmt.Errorf("%s: role %s is missing instructions", source, role.Name)
	}
	return nil
}

func expectedREADMESkillsBlock(repoRoot string) (string, int, error) {
	entries, err := os.ReadDir(filepath.Join(repoRoot, "skills"))
	if errors.Is(err, fs.ErrNotExist) {
		entries = nil
	} else if err != nil {
		return "", 0, fmt.Errorf("read skills/: %w", err)
	}

	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		if !hasFile(filepath.Join(repoRoot, "skills", entry.Name(), "SKILL.md")) {
			continue
		}
		// grill-me is a packaged command alias for grilling, not a standalone
		// model-invocable skill in the public inventory.
		if entry.Name() == "grill-me" {
			continue
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(readmeSkillsBeginMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "%d skills ship with this repo:\n\n", len(names))
	b.WriteString("`")
	b.WriteString(strings.Join(names, "` `"))
	b.WriteString("`\n")
	b.WriteString(readmeSkillsEndMarker)
	return b.String(), len(names), nil
}

func locateREADMESkillsBlock(content string) (int, int, error) {
	if strings.Count(content, readmeSkillsBeginMarker) != 1 || strings.Count(content, readmeSkillsEndMarker) != 1 {
		return 0, 0, errors.New("README skills markers must each appear exactly once")
	}
	start := strings.Index(content, readmeSkillsBeginMarker)
	end := strings.Index(content, readmeSkillsEndMarker)
	if end < start {
		return 0, 0, errors.New("README skills end marker precedes begin marker")
	}
	return start, end + len(readmeSkillsEndMarker), nil
}

func renderREADMESkills(repoRoot string) error {
	path := filepath.Join(repoRoot, "README.md")
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read README.md: %w", err)
	}
	expected, count, err := expectedREADMESkillsBlock(repoRoot)
	if err != nil {
		return err
	}
	content := string(data)
	if !strings.Contains(content, readmeSkillsBeginMarker) && !strings.Contains(content, readmeSkillsEndMarker) {
		return nil
	}
	start, end, err := locateREADMESkillsBlock(content)
	if err != nil {
		return err
	}
	updated := content[:start] + expected + content[end:]
	if updated == content {
		fmt.Printf("rendered README skills: %d unchanged\n", count)
		return nil
	}
	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write README.md: %w", err)
	}
	fmt.Printf("rendered README skills: %d written\n", count)
	return nil
}

func runRender(opts runOptions) error {
	repoRoot, _, _, _, err := loadContext(opts)
	if err != nil {
		return err
	}
	return renderCommittedArtifacts(repoRoot)
}

func renderCommittedArtifacts(repoRoot string) error {
	return renderREADMESkills(repoRoot)
}

func renderAgentRole(role agentRole, agent agentConfig) (string, string, bool) {
	h := harnessFor(agent.Name)
	if h == nil || h.Roles == nil {
		return "", "", false
	}
	if role.Model == "" && agent.RoleModel != "" {
		role.Model = agent.RoleModel
	}
	target := filepath.Join(agent.AgentRoot, role.Name+h.Roles.Extension)
	content := h.Roles.Render(role)
	return target, content, true
}

func renderClaudeAgentRole(role agentRole) string {
	var b strings.Builder
	b.WriteString("---\n")
	writeYAMLScalar(&b, "name", role.Name)
	writeYAMLScalar(&b, "description", role.Description)
	writeYAMLScalar(&b, "model", role.Model)
	writeYAMLScalar(&b, "effort", role.Effort)
	if len(role.Tools) > 0 {
		b.WriteString("tools: ")
		b.WriteString(strings.Join(role.Tools, ", "))
		b.WriteString("\n")
	}
	writeYAMLScalar(&b, "color", role.Color)
	b.WriteString("---\n\n")
	b.WriteString("<!-- ")
	b.WriteString(generatedAgentMarker)
	b.WriteString(" from ")
	b.WriteString(agentRoleSourceLabel(role))
	b.WriteString("; do not edit directly. -->\n\n")
	b.WriteString(role.Instructions)
	b.WriteString("\n")
	return b.String()
}

func renderCodexAgentRole(role agentRole) string {
	model := strings.TrimSpace(role.Codex.Model)
	if model == "" {
		model = codexModelFor(role.Model)
	}
	effort := strings.TrimSpace(role.Codex.ModelReasoningEffort)
	if effort == "" {
		effort = strings.TrimSpace(role.Effort)
	}

	var b strings.Builder
	b.WriteString("# ")
	b.WriteString(generatedAgentMarker)
	b.WriteString(" from ")
	b.WriteString(agentRoleSourceLabel(role))
	b.WriteString("; do not edit directly.\n")
	writeTOMLString(&b, "name", role.Name)
	writeTOMLString(&b, "description", role.Description)
	writeTOMLString(&b, "model", model)
	writeTOMLString(&b, "model_reasoning_effort", effort)
	writeTOMLMultiline(&b, "developer_instructions", role.Instructions)
	return b.String()
}

// codexModelFor resolves legacy canonical model aliases. Claude-family names
// (opus/sonnet/haiku) are not valid Codex identifiers, so they render without a
// model and Codex uses its own default; anything else passes through verbatim.
func codexModelFor(model string) string {
	switch strings.ToLower(strings.TrimSpace(model)) {
	case "", "haiku", "sonnet", "opus":
		return ""
	default:
		return strings.TrimSpace(model)
	}
}

func renderDroidAgentRole(role agentRole) string {
	model := strings.TrimSpace(role.Droid.Model)
	if model == "" {
		model = droidModelFor(role.Model)
	}
	effort := strings.TrimSpace(role.Droid.ReasoningEffort)
	if effort == "" {
		effort = strings.TrimSpace(role.Effort)
	}
	tools := role.Droid.Tools
	if len(tools) == 0 {
		tools = droidToolsFor(role.Tools)
	}

	var b strings.Builder
	b.WriteString("---\n")
	writeYAMLScalar(&b, "name", role.Name)
	writeYAMLScalar(&b, "description", role.Description)
	writeYAMLScalar(&b, "model", model)
	writeYAMLScalar(&b, "reasoningEffort", effort)
	if len(tools) > 0 {
		b.WriteString("tools:\n")
		for _, tool := range tools {
			writeYAMLListItem(&b, tool)
		}
	}
	b.WriteString("---\n\n")
	b.WriteString("<!-- ")
	b.WriteString(generatedAgentMarker)
	b.WriteString(" from ")
	b.WriteString(agentRoleSourceLabel(role))
	b.WriteString("; do not edit directly. -->\n\n")
	b.WriteString(role.Instructions)
	b.WriteString("\n")
	return b.String()
}

func agentRoleSourceLabel(role agentRole) string {
	if role.Source == "" {
		return "agents/" + role.Name + agentRoleMarkdownExt
	}
	return "agents/" + filepath.Base(role.Source)
}

func writeYAMLScalar(b *strings.Builder, key string, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString(key)
	b.WriteString(": ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeYAMLListItem(b *strings.Builder, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString("  - ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeTOMLString(b *strings.Builder, key string, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString(key)
	b.WriteString(" = ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeTOMLMultiline(b *strings.Builder, key string, value string) {
	b.WriteString(key)
	b.WriteString(" = ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func droidModelFor(model string) string {
	model = strings.TrimSpace(model)
	switch strings.ToLower(model) {
	case "haiku":
		return "custom:gpt-5.5(low)"
	case "sonnet":
		return "custom:gpt-5.5(medium)"
	case "opus":
		return "custom:gpt-5.5(high)"
	default:
		if model == "" {
			return "inherit"
		}
		return model
	}
}

func droidToolsFor(tools []string) []string {
	var out []string
	seen := make(map[string]struct{})
	for _, tool := range tools {
		for _, mapped := range droidToolMapping[strings.ToLower(strings.TrimSpace(tool))] {
			if _, ok := seen[mapped]; ok {
				continue
			}
			seen[mapped] = struct{}{}
			out = append(out, mapped)
		}
	}
	if len(tools) > 0 && len(out) == 0 {
		return append([]string(nil), droidFallbackTools...)
	}
	return out
}

func inspectAgentRoles(report *agentReport, repoRoot string, agent agentConfig) error {
	expected, err := expectedAgentRoles(repoRoot, agent)
	if err != nil {
		return err
	}
	if len(expected) == 0 {
		return nil
	}

	names := sortedAgentRoleNames(expected)
	for _, name := range names {
		rendered := expected[name]
		data, err := os.ReadFile(rendered.Target)
		if errors.Is(err, fs.ErrNotExist) {
			report.MissingAgent = append(report.MissingAgent, name)
			report.AddsAgent = append(report.AddsAgent, name)
			continue
		}
		if err != nil {
			return fmt.Errorf("read %s: %w", rendered.Target, err)
		}

		if string(data) == rendered.Content {
			report.ManagedAgent = append(report.ManagedAgent, name)
			continue
		}
		if isManagedAgentFile(rendered.Target, data, repoRoot) {
			report.DriftedAgent = append(report.DriftedAgent, name)
			report.UpdatesAgent = append(report.UpdatesAgent, name)
			continue
		}
		report.Conflicts = append(report.Conflicts, fmt.Sprintf("agent %s exists but is not dotagents-managed", rendered.Target))
	}
	return nil
}

func isManagedAgentFile(path string, data []byte, repoRoot string) bool {
	if strings.Contains(string(data), generatedAgentMarker) {
		return true
	}

	info, err := os.Lstat(path)
	if err != nil || info.Mode()&os.ModeSymlink == 0 {
		return false
	}
	rawTarget, err := os.Readlink(path)
	if err != nil {
		return false
	}
	targetAbs := absoluteTarget(path, rawTarget)
	repoAgentsRoot := filepath.Join(repoRoot, "agents")
	return targetAbs == repoAgentsRoot || strings.HasPrefix(targetAbs, repoAgentsRoot+string(os.PathSeparator))
}

func applyAgentRoleSync(reports []agentReport, selected []agentConfig, repoRoot string) error {
	agentIndex := make(map[string]agentConfig, len(selected))
	for _, agent := range selected {
		agentIndex[agent.Name] = agent
	}
	for _, report := range reports {
		if !report.Detected {
			continue
		}
		agent, ok := agentIndex[report.Name]
		if !ok || agent.AgentRoot == "" {
			continue
		}
		if len(report.Conflicts) > 0 {
			return fmt.Errorf("%s has conflicts", report.Name)
		}
		expected, err := expectedAgentRoles(repoRoot, agent)
		if err != nil {
			return err
		}
		if len(report.AddsAgent)+len(report.UpdatesAgent) == 0 {
			continue
		}
		if err := os.MkdirAll(agent.AgentRoot, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", agent.AgentRoot, err)
		}
		for _, name := range append(append([]string{}, report.AddsAgent...), report.UpdatesAgent...) {
			rendered, ok := expected[name]
			if !ok {
				continue
			}
			if err := os.Remove(rendered.Target); err != nil && !errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("remove %s before rewrite: %w", rendered.Target, err)
			}
			if err := os.WriteFile(rendered.Target, []byte(rendered.Content), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", rendered.Target, err)
			}
		}
	}
	return nil
}

func sortedAgentRoleNames(roles map[string]renderedAgentRole) []string {
	names := make([]string, 0, len(roles))
	for name := range roles {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
