package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedAgentMarker = "Generated by dotagents"

// pluginAgentsRelDir is where committed Claude-format renders of agents/*.yaml
// live. Claude Code auto-discovers plugin subagents from top-level agents/*.md
// only - it does not recurse, and the plugin.json "agents" array does not
// register them (verified empirically) - so the renders sit directly alongside
// the .yaml sources. loadAgentRoles globs *.yaml and ignores the .md, so they
// coexist in the same directory.
const pluginAgentsRelDir = "agents"

type agentRole struct {
	Name         string           `yaml:"name"`
	Description  string           `yaml:"description"`
	Model        string           `yaml:"model"`
	Effort       string           `yaml:"effort"`
	Tools        []string         `yaml:"tools"`
	Color        string           `yaml:"color"`
	Instructions string           `yaml:"instructions"`
	Codex        codexRoleOptions `yaml:"codex"`
	Droid        droidRoleOptions `yaml:"droid"`
}

type codexRoleOptions struct {
	Model                string `yaml:"model"`
	ModelReasoningEffort string `yaml:"model_reasoning_effort"`
}

type droidRoleOptions struct {
	Model           string   `yaml:"model"`
	ReasoningEffort string   `yaml:"reasoning_effort"`
	Tools           []string `yaml:"tools"`
}

var droidToolMapping = map[string][]string{
	"bash":      {"Execute"},
	"edit":      {"Edit"},
	"glob":      {"Glob"},
	"grep":      {"Grep"},
	"read":      {"Read"},
	"webfetch":  {"FetchUrl"},
	"websearch": {"WebSearch"},
	"write":     {"Create", "Edit"},
}

var droidFallbackTools = []string{"Read", "LS", "Grep", "Glob"}

type renderedAgentRole struct {
	Name    string
	Source  string
	Target  string
	Content string
}

func expectedAgentRoles(repoRoot string, agent agentConfig) (map[string]renderedAgentRole, error) {
	if agent.AgentRoot == "" {
		return map[string]renderedAgentRole{}, nil
	}

	roles, err := loadAgentRoles(repoRoot)
	if err != nil {
		return nil, err
	}

	rendered := make(map[string]renderedAgentRole)
	for _, role := range roles {
		target, content, ok := renderAgentRole(role, agent)
		if !ok {
			continue
		}
		rendered[role.Name] = renderedAgentRole{
			Name:    role.Name,
			Source:  filepath.Join(repoRoot, "agents", role.Name+".yaml"),
			Target:  target,
			Content: content,
		}
	}
	return rendered, nil
}

func loadAgentRoles(repoRoot string) ([]agentRole, error) {
	agentsDir := filepath.Join(repoRoot, "agents")
	entries, err := os.ReadDir(agentsDir)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", agentsDir, err)
	}

	var roles []agentRole
	seen := make(map[string]struct{})
	for _, entry := range entries {
		if entry.IsDir() || strings.HasPrefix(entry.Name(), ".") || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		path := filepath.Join(agentsDir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		var role agentRole
		if err := yaml.Unmarshal(data, &role); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		role.Name = normalizeAgentName(role.Name)
		role.Model = strings.TrimSpace(role.Model)
		role.Effort = strings.TrimSpace(role.Effort)
		role.Description = strings.TrimSpace(role.Description)
		role.Instructions = strings.TrimSpace(role.Instructions)
		if role.Name == "" {
			return nil, fmt.Errorf("%s is missing name", path)
		}
		if role.Description == "" {
			return nil, fmt.Errorf("%s is missing description", path)
		}
		if role.Instructions == "" {
			return nil, fmt.Errorf("%s is missing instructions", path)
		}
		if _, ok := seen[role.Name]; ok {
			return nil, fmt.Errorf("agent role %s is duplicated", role.Name)
		}
		seen[role.Name] = struct{}{}
		roles = append(roles, role)
	}
	sort.Slice(roles, func(i, j int) bool {
		return roles[i].Name < roles[j].Name
	})
	return roles, nil
}

func expectedPluginAgentFiles(repoRoot string) (map[string]string, error) {
	roles, err := loadAgentRoles(repoRoot)
	if err != nil {
		return nil, err
	}
	files := make(map[string]string, len(roles))
	for _, role := range roles {
		path := filepath.Join(repoRoot, filepath.FromSlash(pluginAgentsRelDir), role.Name+".md")
		files[path] = renderClaudeAgentRole(role)
	}
	return files, nil
}

func runRender(opts runOptions) error {
	repoRoot, _, _, _, err := loadContext(opts)
	if err != nil {
		return err
	}
	if err := renderPluginAgents(repoRoot); err != nil {
		return err
	}
	return renderCodexPluginSkills(repoRoot)
}

func renderPluginAgents(repoRoot string) error {
	expected, err := expectedPluginAgentFiles(repoRoot)
	if err != nil {
		return err
	}
	dir := filepath.Join(repoRoot, filepath.FromSlash(pluginAgentsRelDir))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}

	written, unchanged := 0, 0
	for path, content := range expected {
		data, err := os.ReadFile(path)
		if err == nil && string(data) == content {
			unchanged++
			continue
		}
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("read %s: %w", path, err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		written++
	}

	removed := 0
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read %s: %w", dir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		if _, ok := expected[path]; ok {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		if !strings.Contains(string(data), generatedAgentMarker) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove stale %s: %w", path, err)
		}
		removed++
	}

	fmt.Printf("rendered %s: %d written, %d unchanged, %d removed\n", pluginAgentsRelDir, written, unchanged, removed)
	return nil
}

func renderAgentRole(role agentRole, agent agentConfig) (string, string, bool) {
	h := harnessFor(agent.Name)
	if h == nil || h.Roles == nil {
		return "", "", false
	}
	target := filepath.Join(agent.AgentRoot, role.Name+h.Roles.Extension)
	content := h.Roles.Render(role)
	return target, content, true
}

func renderClaudeAgentRole(role agentRole) string {
	var b strings.Builder
	b.WriteString("---\n")
	writeYAMLScalar(&b, "name", role.Name)
	writeYAMLScalar(&b, "description", role.Description)
	writeYAMLScalar(&b, "model", role.Model)
	writeYAMLScalar(&b, "effort", role.Effort)
	if len(role.Tools) > 0 {
		b.WriteString("tools: ")
		b.WriteString(strings.Join(role.Tools, ", "))
		b.WriteString("\n")
	}
	writeYAMLScalar(&b, "color", role.Color)
	b.WriteString("---\n\n")
	b.WriteString("<!-- ")
	b.WriteString(generatedAgentMarker)
	b.WriteString(" from agents/")
	b.WriteString(role.Name)
	b.WriteString(".yaml; do not edit directly. -->\n\n")
	b.WriteString(role.Instructions)
	b.WriteString("\n")
	return b.String()
}

func renderCodexAgentRole(role agentRole) string {
	model := strings.TrimSpace(role.Codex.Model)
	if model == "" {
		model = codexModelFor(role.Model)
	}
	effort := strings.TrimSpace(role.Codex.ModelReasoningEffort)
	if effort == "" {
		effort = strings.TrimSpace(role.Effort)
	}

	var b strings.Builder
	b.WriteString("# ")
	b.WriteString(generatedAgentMarker)
	b.WriteString(" from agents/")
	b.WriteString(role.Name)
	b.WriteString(".yaml; do not edit directly.\n")
	writeTOMLString(&b, "name", role.Name)
	writeTOMLString(&b, "description", role.Description)
	writeTOMLString(&b, "model", model)
	writeTOMLString(&b, "model_reasoning_effort", effort)
	writeTOMLMultiline(&b, "developer_instructions", role.Instructions)
	return b.String()
}

func renderDroidAgentRole(role agentRole) string {
	model := strings.TrimSpace(role.Droid.Model)
	if model == "" {
		model = droidModelFor(role.Model)
	}
	effort := strings.TrimSpace(role.Droid.ReasoningEffort)
	if effort == "" {
		effort = strings.TrimSpace(role.Effort)
	}
	tools := role.Droid.Tools
	if len(tools) == 0 {
		tools = droidToolsFor(role.Tools)
	}

	var b strings.Builder
	b.WriteString("---\n")
	writeYAMLScalar(&b, "name", role.Name)
	writeYAMLScalar(&b, "description", role.Description)
	writeYAMLScalar(&b, "model", model)
	writeYAMLScalar(&b, "reasoningEffort", effort)
	if len(tools) > 0 {
		b.WriteString("tools:\n")
		for _, tool := range tools {
			writeYAMLListItem(&b, tool)
		}
	}
	b.WriteString("---\n\n")
	b.WriteString("<!-- ")
	b.WriteString(generatedAgentMarker)
	b.WriteString(" from agents/")
	b.WriteString(role.Name)
	b.WriteString(".yaml; do not edit directly. -->\n\n")
	b.WriteString(role.Instructions)
	b.WriteString("\n")
	return b.String()
}

func writeYAMLScalar(b *strings.Builder, key string, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString(key)
	b.WriteString(": ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeYAMLListItem(b *strings.Builder, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString("  - ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeTOMLString(b *strings.Builder, key string, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	b.WriteString(key)
	b.WriteString(" = ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func writeTOMLMultiline(b *strings.Builder, key string, value string) {
	b.WriteString(key)
	b.WriteString(" = ")
	b.WriteString(strconv.Quote(value))
	b.WriteString("\n")
}

func codexModelFor(model string) string {
	switch strings.ToLower(strings.TrimSpace(model)) {
	case "haiku":
		return "gpt-5.4-mini"
	case "sonnet", "opus":
		return "gpt-5.4"
	default:
		if strings.TrimSpace(model) == "" {
			return "gpt-5.4"
		}
		return strings.TrimSpace(model)
	}
}

func droidModelFor(model string) string {
	model = strings.TrimSpace(model)
	switch strings.ToLower(model) {
	case "haiku":
		return "custom:gpt-5.5(low)"
	case "sonnet":
		return "custom:gpt-5.5(medium)"
	case "opus":
		return "custom:gpt-5.5(high)"
	default:
		if model == "" {
			return "inherit"
		}
		return model
	}
}

func droidToolsFor(tools []string) []string {
	var out []string
	seen := make(map[string]struct{})
	for _, tool := range tools {
		for _, mapped := range droidToolMapping[strings.ToLower(strings.TrimSpace(tool))] {
			if _, ok := seen[mapped]; ok {
				continue
			}
			seen[mapped] = struct{}{}
			out = append(out, mapped)
		}
	}
	if len(tools) > 0 && len(out) == 0 {
		return append([]string(nil), droidFallbackTools...)
	}
	return out
}

func inspectAgentRoles(report *agentReport, repoRoot string, agent agentConfig) error {
	expected, err := expectedAgentRoles(repoRoot, agent)
	if err != nil {
		return err
	}
	if len(expected) == 0 {
		return nil
	}

	names := sortedAgentRoleNames(expected)
	for _, name := range names {
		rendered := expected[name]
		data, err := os.ReadFile(rendered.Target)
		if errors.Is(err, fs.ErrNotExist) {
			report.MissingAgent = append(report.MissingAgent, name)
			report.AddsAgent = append(report.AddsAgent, name)
			continue
		}
		if err != nil {
			return fmt.Errorf("read %s: %w", rendered.Target, err)
		}

		if string(data) == rendered.Content {
			report.ManagedAgent = append(report.ManagedAgent, name)
			continue
		}
		if isManagedAgentFile(rendered.Target, data, repoRoot) {
			report.DriftedAgent = append(report.DriftedAgent, name)
			report.UpdatesAgent = append(report.UpdatesAgent, name)
			continue
		}
		report.Conflicts = append(report.Conflicts, fmt.Sprintf("agent %s exists but is not dotagents-managed", rendered.Target))
	}
	return nil
}

func isManagedAgentFile(path string, data []byte, repoRoot string) bool {
	if strings.Contains(string(data), generatedAgentMarker) {
		return true
	}

	info, err := os.Lstat(path)
	if err != nil || info.Mode()&os.ModeSymlink == 0 {
		return false
	}
	rawTarget, err := os.Readlink(path)
	if err != nil {
		return false
	}
	targetAbs := absoluteTarget(path, rawTarget)
	repoAgentsRoot := filepath.Join(repoRoot, "agents")
	return targetAbs == repoAgentsRoot || strings.HasPrefix(targetAbs, repoAgentsRoot+string(os.PathSeparator))
}

func applyAgentRoleSync(reports []agentReport, selected []agentConfig, repoRoot string) error {
	agentIndex := make(map[string]agentConfig, len(selected))
	for _, agent := range selected {
		agentIndex[agent.Name] = agent
	}
	for _, report := range reports {
		if !report.Detected {
			continue
		}
		agent, ok := agentIndex[report.Name]
		if !ok || agent.AgentRoot == "" {
			continue
		}
		if len(report.Conflicts) > 0 {
			return fmt.Errorf("%s has conflicts", report.Name)
		}
		if usesPluginDelivery(agent) {
			if err := pruneManagedAgentFiles(agent.AgentRoot, report.RemovesAgent); err != nil {
				return err
			}
			continue
		}
		expected, err := expectedAgentRoles(repoRoot, agent)
		if err != nil {
			return err
		}
		if len(report.AddsAgent)+len(report.UpdatesAgent) == 0 {
			continue
		}
		if err := os.MkdirAll(agent.AgentRoot, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", agent.AgentRoot, err)
		}
		for _, name := range append(append([]string{}, report.AddsAgent...), report.UpdatesAgent...) {
			rendered, ok := expected[name]
			if !ok {
				continue
			}
			if err := os.Remove(rendered.Target); err != nil && !errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("remove %s before rewrite: %w", rendered.Target, err)
			}
			if err := os.WriteFile(rendered.Target, []byte(rendered.Content), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", rendered.Target, err)
			}
		}
	}
	return nil
}

func sortedAgentRoleNames(roles map[string]renderedAgentRole) []string {
	names := make([]string, 0, len(roles))
	for name := range roles {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
