package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAgentDeliveryDefaultsToSync(t *testing.T) {
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		SkillRoot: filepath.Join(t.TempDir(), "skills"),
	}}}
	if err := validateConfig(&cfg, t.TempDir(), false); err != nil {
		t.Fatal(err)
	}
	if cfg.Agents[0].Delivery != deliverySync {
		t.Fatalf("delivery = %q, want %q", cfg.Agents[0].Delivery, deliverySync)
	}
}

func TestAgentDeliveryRejectsPluginForNonClaude(t *testing.T) {
	cfg := config{Agents: []agentConfig{{
		Name:      agentCodex,
		Enabled:   true,
		SkillRoot: filepath.Join(t.TempDir(), "skills"),
		Delivery:  deliveryPlugin,
	}}}
	if err := validateConfig(&cfg, t.TempDir(), false); err == nil {
		t.Fatal("validateConfig accepted delivery: plugin for codex")
	}
}

func TestRunSyncPrunesClaudeArtifactsForPluginDelivery(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("DOTAGENTS_ROOT", repoRoot)

	writeSyncTestFile(t, filepath.Join(repoRoot, "dotagents.yaml"), []byte(`version: 1
agents:
  - name: claude-code
    enabled: true
    delivery: plugin
    skill_root: ~/.claude/skills
    agent_root: ~/.claude/agents
`))
	repoSkill := filepath.Join(repoRoot, "skills", "sample")
	writeSyncTestFile(t, filepath.Join(repoSkill, "SKILL.md"), []byte("---\nname: sample\n---\n"))
	writeSyncTestFile(t, filepath.Join(repoRoot, "agents", "helper.yaml"), []byte(`name: helper
description: Help with tests.
model: sonnet
effort: medium
instructions: Test helper.
`))

	claudeSkillRoot := filepath.Join(home, ".claude", "skills")
	claudeAgentRoot := filepath.Join(home, ".claude", "agents")
	if err := os.MkdirAll(claudeSkillRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(claudeAgentRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(repoSkill, filepath.Join(claudeSkillRoot, "sample")); err != nil {
		t.Fatal(err)
	}
	externalSkill := filepath.Join(claudeSkillRoot, "external")
	if err := os.MkdirAll(externalSkill, 0o755); err != nil {
		t.Fatal(err)
	}
	managedAgent := filepath.Join(claudeAgentRoot, "helper.md")
	if err := os.WriteFile(managedAgent, []byte("<!-- Generated by dotagents -->\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	unmanagedAgent := filepath.Join(claudeAgentRoot, "mine.md")
	if err := os.WriteFile(unmanagedAgent, []byte("manual\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := runSync(runOptions{Agents: agentClaudeCode}); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Lstat(filepath.Join(claudeSkillRoot, "sample")); !os.IsNotExist(err) {
		t.Fatalf("managed skill symlink still exists, stat err = %v", err)
	}
	if _, err := os.Stat(externalSkill); err != nil {
		t.Fatalf("external skill was touched: %v", err)
	}
	if _, err := os.Stat(managedAgent); !os.IsNotExist(err) {
		t.Fatalf("managed agent file still exists, stat err = %v", err)
	}
	if _, err := os.Stat(unmanagedAgent); err != nil {
		t.Fatalf("unmanaged agent file was touched: %v", err)
	}
}

func TestClaudeDeliveryCheckPluginInstalled(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	agent := agentConfig{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliveryPlugin,
		SkillRoot: filepath.Join(home, ".claude", "skills"),
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}
	cfg := config{Agents: []agentConfig{agent}}
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [
      {
        "scope": "user",
        "installPath": "/tmp/dotagents",
        "version": "unknown"
      }
    ]
  }
}`))

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusPass {
		t.Fatalf("status = %s (%s), want pass", result.status, result.detail)
	}
}

func TestClaudeDeliveryCheckPluginAbsentFailsPluginMode(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliveryPlugin,
		SkillRoot: filepath.Join(home, ".claude", "skills"),
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}}}

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusFail {
		t.Fatalf("status = %s (%s), want fail", result.status, result.detail)
	}
	if !strings.Contains(result.detail, "dotagents plugin add") {
		t.Fatalf("detail = %q, want plugin add hint", result.detail)
	}
}

func TestClaudeDeliveryCheckFailsPluginModeWithManagedArtifacts(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	repoSkill := filepath.Join(repoRoot, "skills", "sample")
	writeSyncTestFile(t, filepath.Join(repoSkill, "SKILL.md"), []byte("---\nname: sample\n---\n"))
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [{"scope": "user"}]
  }
}`))
	skillRoot := filepath.Join(home, ".claude", "skills")
	if err := os.MkdirAll(skillRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(repoSkill, filepath.Join(skillRoot, "sample")); err != nil {
		t.Fatal(err)
	}
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliveryPlugin,
		SkillRoot: skillRoot,
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}}}

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusFail {
		t.Fatalf("status = %s (%s), want fail", result.status, result.detail)
	}
	if !strings.Contains(result.detail, "managed sync artifacts remain") {
		t.Fatalf("detail = %q, want stale artifact detail", result.detail)
	}
}

func TestClaudeDeliveryCheckWarnsWhenPluginInstalledInSyncMode(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliverySync,
		SkillRoot: filepath.Join(home, ".claude", "skills"),
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}}}
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [{"scope": "user"}]
  }
}`))

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusWarn {
		t.Fatalf("status = %s (%s), want warn", result.status, result.detail)
	}
}
