package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAgentDeliveryRejectsPluginForNonClaude(t *testing.T) {
	cfg := config{Agents: []agentConfig{{
		Name:      agentCodex,
		Enabled:   true,
		SkillRoot: filepath.Join(t.TempDir(), "skills"),
		Delivery:  deliveryPlugin,
	}}}
	if err := validateConfig(&cfg, t.TempDir(), false); err == nil {
		t.Fatal("validateConfig accepted delivery: plugin for codex")
	}
}

func TestRunSyncPrunesClaudeArtifactsForPluginDelivery(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("DOTAGENTS_ROOT", repoRoot)

	writeSyncTestFile(t, filepath.Join(repoRoot, "dotagents.yaml"), []byte(`version: 1
agents:
  - name: claude-code
    enabled: true
    delivery: plugin
    skill_root: ~/.claude/skills
    agent_root: ~/.claude/agents
`))
	repoSkill := filepath.Join(repoRoot, "skills", "sample")
	writeSyncTestFile(t, filepath.Join(repoSkill, "SKILL.md"), []byte("---\nname: sample\n---\n"))
	writeSyncTestFile(t, filepath.Join(repoRoot, "agents", "helper.yaml"), []byte(`name: helper
description: Help with tests.
model: sonnet
effort: medium
instructions: Test helper.
`))

	claudeSkillRoot := filepath.Join(home, ".claude", "skills")
	claudeAgentRoot := filepath.Join(home, ".claude", "agents")
	if err := os.MkdirAll(claudeSkillRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(claudeAgentRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(repoSkill, filepath.Join(claudeSkillRoot, "sample")); err != nil {
		t.Fatal(err)
	}
	externalSkill := filepath.Join(claudeSkillRoot, "external")
	if err := os.MkdirAll(externalSkill, 0o755); err != nil {
		t.Fatal(err)
	}
	managedAgent := filepath.Join(claudeAgentRoot, "helper.md")
	if err := os.WriteFile(managedAgent, []byte("<!-- Generated by dotagents -->\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	unmanagedAgent := filepath.Join(claudeAgentRoot, "mine.md")
	if err := os.WriteFile(unmanagedAgent, []byte("manual\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := runSync(runOptions{Agents: agentClaudeCode}); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Lstat(filepath.Join(claudeSkillRoot, "sample")); !os.IsNotExist(err) {
		t.Fatalf("managed skill symlink still exists, stat err = %v", err)
	}
	if _, err := os.Stat(externalSkill); err != nil {
		t.Fatalf("external skill was touched: %v", err)
	}
	if _, err := os.Stat(managedAgent); !os.IsNotExist(err) {
		t.Fatalf("managed agent file still exists, stat err = %v", err)
	}
	if _, err := os.Stat(unmanagedAgent); err != nil {
		t.Fatalf("unmanaged agent file was touched: %v", err)
	}
}

func TestRunSyncManagesPluginSkillsForClaudePluginDelivery(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("DOTAGENTS_ROOT", repoRoot)

	pluginSource := filepath.Join(home, "plugins", "browser")
	currentSkillDir := filepath.Join(pluginSource, "2.0.0", "skills", "browser-skill")
	writeSyncTestFile(t, filepath.Join(currentSkillDir, "SKILL.md"), []byte("---\nname: browser-skill\n---\n"))

	writeSyncTestFile(t, filepath.Join(repoRoot, "dotagents.yaml"), []byte(`version: 1
agents:
  - name: claude-code
    enabled: true
    delivery: plugin
    skill_root: ~/.claude/skills
    agent_root: ~/.claude/agents
plugins:
  - name: browser
    enabled: true
    source: `+pluginSource+`
    format: codex-plugin
    surfaces:
      - skills
    agents:
      - claude-code
`))

	claudeSkillRoot := filepath.Join(home, ".claude", "skills")
	if err := os.MkdirAll(claudeSkillRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	staleLink := filepath.Join(claudeSkillRoot, "dropped-skill")
	if err := os.Symlink(filepath.Join(pluginSource, "1.0.0", "skills", "dropped-skill"), staleLink); err != nil {
		t.Fatal(err)
	}

	if err := runSync(runOptions{Agents: agentClaudeCode}); err != nil {
		t.Fatal(err)
	}

	linked, err := os.Readlink(filepath.Join(claudeSkillRoot, "browser-skill"))
	if err != nil {
		t.Fatalf("expected plugin skill symlink: %v", err)
	}
	if linked != currentSkillDir {
		t.Fatalf("browser-skill -> %s, want %s", linked, currentSkillDir)
	}
	if _, err := os.Lstat(staleLink); !os.IsNotExist(err) {
		t.Fatalf("stale plugin link still exists, stat err = %v", err)
	}
}

func TestClaudeDeliveryCheckPluginInstalled(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	agent := agentConfig{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliveryPlugin,
		SkillRoot: filepath.Join(home, ".claude", "skills"),
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}
	cfg := config{Agents: []agentConfig{agent}}
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [
      {
        "scope": "user",
        "installPath": "/tmp/dotagents",
        "version": "unknown"
      }
    ]
  }
}`))

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusPass {
		t.Fatalf("status = %s (%s), want pass", result.status, result.detail)
	}
}

func TestClaudeDeliveryCheckPluginAbsentFailsPluginMode(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliveryPlugin,
		SkillRoot: filepath.Join(home, ".claude", "skills"),
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}}}

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusFail {
		t.Fatalf("status = %s (%s), want fail", result.status, result.detail)
	}
	const want = "delivery=plugin but dotagents@yourconscience is not installed; run: dotagents setup --delivery plugin"
	if result.detail != want {
		t.Fatalf("detail = %q, want %q", result.detail, want)
	}
}

func TestClaudeDeliveryCheckFailsPluginModeWithManagedArtifacts(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	repoSkill := filepath.Join(repoRoot, "skills", "sample")
	writeSyncTestFile(t, filepath.Join(repoSkill, "SKILL.md"), []byte("---\nname: sample\n---\n"))
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [{"scope": "user"}]
  }
}`))
	skillRoot := filepath.Join(home, ".claude", "skills")
	if err := os.MkdirAll(skillRoot, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(repoSkill, filepath.Join(skillRoot, "sample")); err != nil {
		t.Fatal(err)
	}
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliveryPlugin,
		SkillRoot: skillRoot,
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}}}

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusFail {
		t.Fatalf("status = %s (%s), want fail", result.status, result.detail)
	}
	if !strings.Contains(result.detail, "managed sync artifacts remain") {
		t.Fatalf("detail = %q, want stale artifact detail", result.detail)
	}
}

func TestClaudeDeliveryCheckFailsWhenPluginInstalledInSyncMode(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	cfg := config{Agents: []agentConfig{{
		Name:      agentClaudeCode,
		Enabled:   true,
		Delivery:  deliverySync,
		SkillRoot: filepath.Join(home, ".claude", "skills"),
		AgentRoot: filepath.Join(home, ".claude", "agents"),
	}}}
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [{"scope": "user"}]
  }
}`))

	result := checkClaudeDelivery(repoRoot, home, cfg)
	if result.status != checkStatusFail {
		t.Fatalf("status = %s (%s), want fail", result.status, result.detail)
	}
	const want = "delivery=sync but dotagents@yourconscience is installed; run: dotagents setup --delivery sync, or: dotagents setup --delivery plugin"
	if result.detail != want {
		t.Fatalf("detail = %q, want %q", result.detail, want)
	}
}

func TestClaudeDeliveryConflictFailsSetupStatusAndSync(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("DOTAGENTS_ROOT", repoRoot)

	writeSyncTestFile(t, filepath.Join(repoRoot, "dotagents.yaml"), []byte(`version: 1
agents:
  - name: claude-code
    enabled: true
    delivery: sync
    skill_root: ~/.claude/skills
    agent_root: ~/.claude/agents
  - name: codex
    enabled: true
    skill_root: ~/.codex/skills
    agent_root: ~/.codex/agents
`))
	writeSyncTestFile(t, filepath.Join(home, ".claude", "plugins", "installed_plugins.json"), []byte(`{
  "version": 2,
  "plugins": {
    "dotagents@yourconscience": [{"scope": "user"}]
  }
}`))

	const want = "claude delivery conflict: delivery=sync but dotagents@yourconscience is installed; run: dotagents setup --delivery sync, or: dotagents setup --delivery plugin"
	for _, command := range []string{"setup", "status", "sync"} {
		t.Run(command, func(t *testing.T) {
			err := run([]string{command, "--agents=codex"})
			if err == nil || err.Error() != want {
				t.Fatalf("dotagents %s error = %v, want %q", command, err, want)
			}
		})
	}
}

func TestClaudeOrphanPluginCacheIgnoresSiblingMarketplaceCache(t *testing.T) {
	home := t.TempDir()
	siblingFile := filepath.Join(home, ".claude", "plugins", "cache", claudeDotagentsMarketplace, "tech-search", "1.0.0", "plugin.json")
	writeSyncTestFile(t, siblingFile, []byte("tech-search cache\n"))

	result := checkClaudeOrphanPluginCache(home)
	if result.status != checkStatusPass {
		t.Fatalf("sibling marketplace cache produced %s (%s), want pass", result.status, result.detail)
	}
}

func TestClaudeOrphanPluginCacheWarnsForDotagentsVersion(t *testing.T) {
	home := t.TempDir()
	cachePath := claudeDotagentsPluginCachePath(home)
	writeSyncTestFile(t, filepath.Join(cachePath, "1.0.0", "plugin.json"), []byte("dotagents cache\n"))

	result := checkClaudeOrphanPluginCache(home)
	if result.status != checkStatusWarn {
		t.Fatalf("orphan dotagents cache produced %s (%s), want warn", result.status, result.detail)
	}
	want := cachePath + " exists but dotagents is absent from installed_plugins.json; run: dotagents setup --delivery sync"
	if result.detail != want {
		t.Fatalf("detail = %q, want %q", result.detail, want)
	}
}

func TestSetupSyncDeliveryRemovesOnlyDotagentsClaudeCacheAndClearsWarning(t *testing.T) {
	home := t.TempDir()
	repoRoot := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("DOTAGENTS_ROOT", repoRoot)
	fakeBin := t.TempDir()
	if err := os.WriteFile(filepath.Join(fakeBin, "dotagents"), []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", fakeBin)

	configPath := filepath.Join(repoRoot, "dotagents.yaml")
	writeSyncTestFile(t, configPath, []byte(`version: 1
agents:
  - name: claude-code
    enabled: true
    delivery: plugin
    skill_root: ~/.claude/skills
    agent_root: ~/.claude/agents
`))
	dotagentsCache := claudeDotagentsPluginCachePath(home)
	writeSyncTestFile(t, filepath.Join(dotagentsCache, "1.0.0", "plugin.json"), []byte("dotagents cache\n"))
	siblingFile := filepath.Join(home, ".claude", "plugins", "cache", claudeDotagentsMarketplace, "tech-search", "2.0.0", "plugin.json")
	const siblingContent = "tech-search cache\n"
	writeSyncTestFile(t, siblingFile, []byte(siblingContent))

	before := checkClaudeOrphanPluginCache(home)
	if before.status != checkStatusWarn {
		t.Fatalf("precondition: orphan dotagents cache produced %s (%s), want warn", before.status, before.detail)
	}
	if err := run([]string{"setup", "--delivery=sync", "--config", configPath}); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Lstat(dotagentsCache); !os.IsNotExist(err) {
		t.Fatalf("dotagents cache still exists after sync delivery, stat err = %v", err)
	}
	siblingData, err := os.ReadFile(siblingFile)
	if err != nil {
		t.Fatalf("sibling marketplace cache was removed: %v", err)
	}
	if string(siblingData) != siblingContent {
		t.Fatalf("sibling marketplace cache = %q, want %q", siblingData, siblingContent)
	}
	after := checkClaudeOrphanPluginCache(home)
	if after.status != checkStatusPass {
		t.Fatalf("sync-delivery remediation left %s (%s), want pass", after.status, after.detail)
	}
}
